### ISSUE TITLE
Error reading M3

### ISSUE THREAD

**Issue by galfridus** [amorphous1/hf4_to_ebook#2]
Error reading Module 3 PDF from 2021-10-09:

Traceback (most recent call last):
  File "C:\Users\geoff\Documents\GitHub\hf4_to_ebook\main.py", line 127, in <module>
    out.write(extract_page(right, 2 * pagenum + 3 + 100 * docnum))
  File "C:\Users\geoff\Documents\GitHub\hf4_to_ebook\main.py", line 116, in extract_page
    return page_comment + extract_main_section(main_section, rects)
  File "C:\Users\geoff\Documents\GitHub\hf4_to_ebook\main.py", line 92, in extract_main_section
    markdown += add_markup(text, fontname)
  File "C:\Users\geoff\Documents\GitHub\hf4_to_ebook\main.py", line 66, in add_markup
    return "".join([hf4_letter_to_starsign[ch] for ch in text])
  File "C:\Users\geoff\Documents\GitHub\hf4_to_ebook\main.py", line 66, in <listcomp>
    return "".join([hf4_letter_to_starsign[ch] for ch in text])
KeyError: 'B'

**Comment by amorphous1** [comment]
I don't own (and don't intend to buy) module 3, so this was not supported. For completeness. I added in the basics to not blow up like the above. I did not double-check the output though, and suspect some of the tables will be a bit mangled in the markdown. Might be enough to check if something has changed in there.
